start: "(FPCore (x) " body ")"
body: e0 | "(if " cond " " body " " body ")"
cond: "(< " operand " " operand ")" | "(> " operand " " operand ")" | "(<= " operand " " operand ")" | "(>= " operand " " operand ")"
operand: "x" | NUMBER
NUMBER: /-?[0-9]+(\.[0-9]+)?/
e0: "(/ " e1 " " e2 ")"
e1: "(/ " e3 " " e4 ")"
e2: "(+ " e4 " " e5 ")" | "(+ " e5 " " e4 ")" | "(- " e4 " " e3 ")"
e3: "1"
e4: "x"
e5: "-1"
